name: english_words_app
description: A Flutter app to manage and explore English words.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  sqflite: ^2.0.0+4
  path_provider: ^2.0.3
  go_router: ^5.0.1
  just_audio: ^0.9.46

  cupertino_icons: ^1.0.6
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/words_dictionary.json
